name: ci
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:


permissions:
  contents: read

jobs:
  set-env:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "CALENDAR_PROVIDER=msgraph" >> $GITHUB_ENV

  plugin-ci:
    uses: mattermost/actions-workflows/.github/workflows/plugin-ci.yml@main
    secrets: inherit
